version: '3.9'

services:
  mongo:
    image: mongo:6.0
    container_name: humami-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    profiles: ["local", "prod"]
  backend:
    build:
      context: ./humami-backend
      dockerfile: Dockerfile
    container_name: humami-backend
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file:
      - .env      
    environment:
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
    profiles: ["local", "prod"]

  frontend:
    build:
      context: ./humami-web
      dockerfile: Dockerfile
    container_name: humami-frontend
    expose:
      - "3000"
    ports:
      - "3000:3000"  # Solo útil en local
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    profiles: ["local", "prod"]

  nginx:
    image: nginx:alpine
    container_name: humami-nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    profiles: ["prod"]

  certbot:
    image: certbot/certbot
    container_name: humami-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    profiles: ["prod"]

volumes:
  mongo-data:
